-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 15:03:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema labo_dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `labo_dev` ;

-- -----------------------------------------------------
-- Schema labo_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labo_dev` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `labo_dev` ;

-- -----------------------------------------------------
-- Table `labo_dev`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`brands` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`brands` (
  `id` INT NOT NULL,
  `brandName` VARCHAR(50) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`types` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type` (`type` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`users` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  `emailVerifyAt` TIMESTAMP NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `typeUser` VARCHAR(20) NULL DEFAULT NULL,
  `type_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_id` (`type_id` ASC) VISIBLE,
  CONSTRAINT `type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `labo_dev`.`types` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`locations` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`locations` (
  `id` INT NOT NULL,
  `locationName` VARCHAR(20) NULL DEFAULT NULL,
  `shelfNumber` INT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`documentTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`documentTypes` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`documentTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`documents` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(150) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  `type_documentTypes` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug` (`slug` ASC) VISIBLE,
  INDEX `type_documentTypes` (`type_documentTypes` ASC) VISIBLE,
  CONSTRAINT `type_documentTypes`
    FOREIGN KEY (`type_documentTypes`)
    REFERENCES `labo_dev`.`documentTypes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`models` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`models` (
  `id` INT NOT NULL,
  `modelName` VARCHAR(50) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  `type_brands` INT NULL DEFAULT NULL,
  `type_documents` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_brands` (`type_brands` ASC) VISIBLE,
  INDEX `type_documents` (`type_documents` ASC) VISIBLE,
  CONSTRAINT `type_brands`
    FOREIGN KEY (`type_brands`)
    REFERENCES `labo_dev`.`brands` (`id`),
  CONSTRAINT `type_documents`
    FOREIGN KEY (`type_documents`)
    REFERENCES `labo_dev`.`documents` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`devices` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deviceRef` VARCHAR(100) NULL DEFAULT NULL,
  `serialNumber` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `users_id` INT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  `brand` VARCHAR(100) NULL DEFAULT NULL,
  `model` VARCHAR(50) NULL DEFAULT NULL,
  `location` VARCHAR(20) NULL DEFAULT NULL,
  `type_models` INT NULL DEFAULT NULL,
  `type_locations` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `deviceRef` (`deviceRef` ASC) VISIBLE,
  INDEX `FK_DeviceUser` (`users_id` ASC) VISIBLE,
  INDEX `type_models` (`type_models` ASC) VISIBLE,
  INDEX `type_locations` (`type_locations` ASC) VISIBLE,
  CONSTRAINT `FK_DeviceUser`
    FOREIGN KEY (`users_id`)
    REFERENCES `labo_dev`.`users` (`id`),
  CONSTRAINT `type_locations`
    FOREIGN KEY (`type_locations`)
    REFERENCES `labo_dev`.`locations` (`id`),
  CONSTRAINT `type_models`
    FOREIGN KEY (`type_models`)
    REFERENCES `labo_dev`.`models` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`shelves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`shelves` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`shelves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  `type_locations` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_locations` (`type_locations` ASC) VISIBLE,
  CONSTRAINT `shelves_ibfk_1`
    FOREIGN KEY (`type_locations`)
    REFERENCES `labo_dev`.`locations` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `labo_dev`.`users_devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_dev`.`users_devices` ;

CREATE TABLE IF NOT EXISTS `labo_dev`.`users_devices` (
  `users_id` INT NOT NULL,
  `devices_id` INT NOT NULL,
  `borrowedAt` TIMESTAMP NULL DEFAULT NULL,
  `returnedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`users_id`, `devices_id`),
  INDEX `devices_id` (`devices_id` ASC) VISIBLE,
  CONSTRAINT `users_devices_ibfk_1`
    FOREIGN KEY (`users_id`)
    REFERENCES `labo_dev`.`users` (`id`),
  CONSTRAINT `users_devices_ibfk_2`
    FOREIGN KEY (`devices_id`)
    REFERENCES `labo_dev`.`devices` (`id`),
  CONSTRAINT `users_devices_ibfk_3`
    FOREIGN KEY (`users_id`)
    REFERENCES `labo_dev`.`users` (`id`),
  CONSTRAINT `users_devices_ibfk_4`
    FOREIGN KEY (`devices_id`)
    REFERENCES `labo_dev`.`devices` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
