<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2hTyfT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2hTyfT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS2hTyfT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS2hTyfT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS2hTyfT\App_KernelDevDebugContainer([
    'container.build_hash' => 'S2hTyfT',
    'container.build_id' => '81dfa383',
    'container.build_time' => 1701959747,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS2hTyfT');
